PASSWORD_MIN_LENGTH = 6

ABOUT_ROWS = 4

SKILL_NAME_MAX_LENGTH = 124

USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_ABOUT_MAX_LENGTH = 256

PHONE_MAX_LENGTH = 12

AVATAR_SIZE = 200

FONT_BASE_PATH_LINUX = '/usr/share/fonts/truetype/'
FONT_BASE_PATH_WINDOWS = 'C:/Windows/Fonts/'
FONT_BASE_PATH_MAC = '/System/Library/Fonts/'

COLOR_LIGHT_BLUE = (52, 152, 219)
COLOR_GREEN = (46, 204, 113)
COLOR_PURPLE = (155, 89, 182)
COLOR_DARK_BLUE = (52, 73, 94)
COLOR_PINK = (241, 76, 139)
COLOR_ORANGE = (243, 156, 18)
COLOR_BLUE = (41, 128, 185)
COLOR_CARROT = (230, 126, 34)
COLOR_EMERALD = (39, 174, 96)
COLOR_WHITE = (255, 255, 255)

COLORS = [COLOR_BLUE, COLOR_CARROT, COLOR_DARK_BLUE, COLOR_EMERALD,
          COLOR_GREEN, COLOR_LIGHT_BLUE, COLOR_ORANGE, COLOR_PINK,
          COLOR_PURPLE]

FONT_PATHS = [
    # Linux
    FONT_BASE_PATH_LINUX + 'dejavu/DejaVuSans.ttf',
    FONT_BASE_PATH_LINUX + 'liberation/LiberationSans-Regular.ttf',
    # Windows
    FONT_BASE_PATH_WINDOWS + 'arial.ttf',
    FONT_BASE_PATH_WINDOWS + 'segoeui.ttf',
    # Mac
    FONT_BASE_PATH_MAC + 'Helvetica.ttc',
]

AUTOCOMPLETE_LIMIT = 10
